//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partnerinfo.Identity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityAppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityAppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Partnerinfo.Identity.IdentityAppResources", typeof(IdentityAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string Account_AccountMessageType_ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("Account_AccountMessageType_ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string Account_AccountMessageType_RemoveLoginSuccess {
            get {
                return ResourceManager.GetString("Account_AccountMessageType_RemoveLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string Account_AccountMessageType_SetPasswordSuccess {
            get {
                return ResourceManager.GetString("Account_AccountMessageType_SetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your Partnerinfo TV account with a new account.
        /// </summary>
        public static string Account_AssociateWith {
            get {
                return ResourceManager.GetString("Account_AssociateWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_AssociateWithDescription {
            get {
                return ResourceManager.GetString("Account_AssociateWithDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Account_Birthday_Day {
            get {
                return ResourceManager.GetString("Account_Birthday_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Account_Birthday_Month {
            get {
                return ResourceManager.GetString("Account_Birthday_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Account_Birthday_Year {
            get {
                return ResourceManager.GetString("Account_Birthday_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Account_ChangePassword {
            get {
                return ResourceManager.GetString("Account_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Account_CreateNew {
            get {
                return ResourceManager.GetString("Account_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        public static string Account_ForgottenPassword {
            get {
                return ResourceManager.GetString("Account_ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Account_LogIn {
            get {
                return ResourceManager.GetString("Account_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with external account.
        /// </summary>
        public static string Account_LoginWithOAuth {
            get {
                return ResourceManager.GetString("Account_LoginWithOAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Account_LogOut {
            get {
                return ResourceManager.GetString("Account_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_OAuthLoginConfirmation {
            get {
                return ResourceManager.GetString("Account_OAuthLoginConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_OAuthLoginFailure {
            get {
                return ResourceManager.GetString("Account_OAuthLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string Account_PasswordError {
            get {
                return ResourceManager.GetString("Account_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password settings.
        /// </summary>
        public static string Account_PasswordSettings {
            get {
                return ResourceManager.GetString("Account_PasswordSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile data with extra services.
        /// </summary>
        public static string Account_ProfileData {
            get {
                return ResourceManager.GetString("Account_ProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you dislike .
        /// </summary>
        public static string Account_ProvidersDescription {
            get {
                return ResourceManager.GetString("Account_ProvidersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string Account_SetPassword {
            get {
                return ResourceManager.GetString("Account_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local password for this site. Add a local password so you can log in without an external login..
        /// </summary>
        public static string Account_SetPasswordDescription {
            get {
                return ResourceManager.GetString("Account_SetPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account settings.
        /// </summary>
        public static string Account_Settings {
            get {
                return ResourceManager.GetString("Account_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Facebook.
        /// </summary>
        public static string Account_SigninWithFacebook {
            get {
                return ResourceManager.GetString("Account_SigninWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string Account_Signup {
            get {
                return ResourceManager.GetString("Account_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string AccountPassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("AccountPassword_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string AccountPassword_ConfirmPassword_Compare {
            get {
                return ResourceManager.GetString("AccountPassword_ConfirmPassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string AccountPassword_NewPassword {
            get {
                return ResourceManager.GetString("AccountPassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string AccountPassword_NewPassword_StringLength {
            get {
                return ResourceManager.GetString("AccountPassword_NewPassword_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string AccountPassword_OldPassword {
            get {
                return ResourceManager.GetString("AccountPassword_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old password is required..
        /// </summary>
        public static string AccountPassword_OldPassword_Required {
            get {
                return ResourceManager.GetString("AccountPassword_OldPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginInfo {
            get {
                return ResourceManager.GetString("LoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginInfo_Email {
            get {
                return ResourceManager.GetString("LoginInfo_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address of the user is invalid..
        /// </summary>
        public static string LoginInfo_Email_RegularExpression {
            get {
                return ResourceManager.GetString("LoginInfo_Email_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address of the user is required..
        /// </summary>
        public static string LoginInfo_Email_Required {
            get {
                return ResourceManager.GetString("LoginInfo_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address of the user cannot exceed {1} characters..
        /// </summary>
        public static string LoginInfo_Email_StringLength {
            get {
                return ResourceManager.GetString("LoginInfo_Email_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginInfo_Password {
            get {
                return ResourceManager.GetString("LoginInfo_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password of the user is required..
        /// </summary>
        public static string LoginInfo_Password_Required {
            get {
                return ResourceManager.GetString("LoginInfo_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password of the user cannot less than {2} characters..
        /// </summary>
        public static string LoginInfo_Password_StringLength {
            get {
                return ResourceManager.GetString("LoginInfo_Password_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string LoginInfo_RememberMe {
            get {
                return ResourceManager.GetString("LoginInfo_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address already exists in the database for the application..
        /// </summary>
        public static string MembershipCreateStatus_DuplicateEmail {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider user key already exists in the database for the application..
        /// </summary>
        public static string MembershipCreateStatus_DuplicateProviderUserKey {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_DuplicateProviderUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name already exists in the database for the application..
        /// </summary>
        public static string MembershipCreateStatus_DuplicateUserName {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password answer is not formatted correctly..
        /// </summary>
        public static string MembershipCreateStatus_InvalidAnswer {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address is not formatted correctly..
        /// </summary>
        public static string MembershipCreateStatus_InvalidEmail {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is not formatted correctly..
        /// </summary>
        public static string MembershipCreateStatus_InvalidPassword {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider user key is of an invalid type or format..
        /// </summary>
        public static string MembershipCreateStatus_InvalidProviderUserKey {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidProviderUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password question is not formatted correctly..
        /// </summary>
        public static string MembershipCreateStatus_InvalidQuestion {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name was not found in the database..
        /// </summary>
        public static string MembershipCreateStatus_InvalidUserName {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider returned an error that is not described by other UserCreateStatus enumeration values..
        /// </summary>
        public static string MembershipCreateStatus_ProviderError {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was successfully created..
        /// </summary>
        public static string MembershipCreateStatus_Success {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was not created, for a reason defined by the provider..
        /// </summary>
        public static string MembershipCreateStatus_UserRejected {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password..
        /// </summary>
        public static string MembershipLogInStatus_InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("MembershipLogInStatus_InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string SignupInfo_Birthday {
            get {
                return ResourceManager.GetString("SignupInfo_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birthday must be between {1} and {2}..
        /// </summary>
        public static string SignupInfo_Birthday_YearRange {
            get {
                return ResourceManager.GetString("SignupInfo_Birthday_YearRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SignupInfo_Email {
            get {
                return ResourceManager.GetString("SignupInfo_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is invalid..
        /// </summary>
        public static string SignupInfo_Email_RegularExpression {
            get {
                return ResourceManager.GetString("SignupInfo_Email_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address of the user is required..
        /// </summary>
        public static string SignupInfo_Email_Required {
            get {
                return ResourceManager.GetString("SignupInfo_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address cannot exceed {1} characters..
        /// </summary>
        public static string SignupInfo_Email_StringLength {
            get {
                return ResourceManager.GetString("SignupInfo_Email_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string SignupInfo_FirstName {
            get {
                return ResourceManager.GetString("SignupInfo_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name cannot exceed {1} characters..
        /// </summary>
        public static string SignupInfo_FirstName_StringLength {
            get {
                return ResourceManager.GetString("SignupInfo_FirstName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string SignupInfo_Gender {
            get {
                return ResourceManager.GetString("SignupInfo_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string SignupInfo_LastName {
            get {
                return ResourceManager.GetString("SignupInfo_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name cannot exceed {1} characters..
        /// </summary>
        public static string SignupInfo_LastName_StringLength {
            get {
                return ResourceManager.GetString("SignupInfo_LastName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SignupInfo_Name {
            get {
                return ResourceManager.GetString("SignupInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SignupInfo_Password {
            get {
                return ResourceManager.GetString("SignupInfo_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password of the user is required..
        /// </summary>
        public static string SignupInfo_Password_Required {
            get {
                return ResourceManager.GetString("SignupInfo_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password of the user cannot less than {2} characters..
        /// </summary>
        public static string SignupInfo_Password_StringLength {
            get {
                return ResourceManager.GetString("SignupInfo_Password_StringLength", resourceCulture);
            }
        }
    }
}
