//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partnerinfo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Partnerinfo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to birthday.
        /// </summary>
        public static string TemplateField_Birthday {
            get {
                return ResourceManager.GetString("TemplateField_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string TemplateField_Comment {
            get {
                return ResourceManager.GetString("TemplateField_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string TemplateField_Email_Address {
            get {
                return ResourceManager.GetString("TemplateField_Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string TemplateField_Email_Name {
            get {
                return ResourceManager.GetString("TemplateField_Email_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstname.
        /// </summary>
        public static string TemplateField_FirstName {
            get {
                return ResourceManager.GetString("TemplateField_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gender.
        /// </summary>
        public static string TemplateField_Gender {
            get {
                return ResourceManager.GetString("TemplateField_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string TemplateField_Invitation_From {
            get {
                return ResourceManager.GetString("TemplateField_Invitation_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        public static string TemplateField_Invitation_Message {
            get {
                return ResourceManager.GetString("TemplateField_Invitation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lastname.
        /// </summary>
        public static string TemplateField_LastName {
            get {
                return ResourceManager.GetString("TemplateField_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nickname.
        /// </summary>
        public static string TemplateField_NickName {
            get {
                return ResourceManager.GetString("TemplateField_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.business.
        /// </summary>
        public static string TemplateField_Phones_Business {
            get {
                return ResourceManager.GetString("TemplateField_Phones_Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.mobile.
        /// </summary>
        public static string TemplateField_Phones_Mobile {
            get {
                return ResourceManager.GetString("TemplateField_Phones_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.other.
        /// </summary>
        public static string TemplateField_Phones_Other {
            get {
                return ResourceManager.GetString("TemplateField_Phones_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.personal.
        /// </summary>
        public static string TemplateField_Phones_Personal {
            get {
                return ResourceManager.GetString("TemplateField_Phones_Personal", resourceCulture);
            }
        }
    }
}
