//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Partnerinfo.Drive {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DriveResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DriveResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Partnerinfo.Drive.DriveResources", typeof(DriveResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create document.
        /// </summary>
        public static string Command_CreateNewDocument {
            get {
                return ResourceManager.GetString("Command_CreateNewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        public static string Command_CreateNewFolder {
            get {
                return ResourceManager.GetString("Command_CreateNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract content (Zip archive).
        /// </summary>
        public static string Command_ExtractDocumentFile {
            get {
                return ResourceManager.GetString("Command_ExtractDocumentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new option.
        /// </summary>
        public static string Command_Form_AddNewOption {
            get {
                return ResourceManager.GetString("Command_Form_AddNewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Command_Form_MoveToNext {
            get {
                return ResourceManager.GetString("Command_Form_MoveToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Command_Form_MoveToPrevious {
            get {
                return ResourceManager.GetString("Command_Form_MoveToPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Command_Form_Submit {
            get {
                return ResourceManager.GetString("Command_Form_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file you would like to share....
        /// </summary>
        public static string Command_SelectDocumentFile {
            get {
                return ResourceManager.GetString("Command_SelectDocumentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse or drop files here to upload.
        /// </summary>
        public static string Command_UploadDocumentFile {
            get {
                return ResourceManager.GetString("Command_UploadDocumentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Document_Length {
            get {
                return ResourceManager.GetString("Document_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Document_Name {
            get {
                return ResourceManager.GetString("Document_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the document is required..
        /// </summary>
        public static string Document_Name_Required {
            get {
                return ResourceManager.GetString("Document_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the document cannot exceed {1} characters..
        /// </summary>
        public static string Document_Name_StringLength {
            get {
                return ResourceManager.GetString("Document_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Document_Owner {
            get {
                return ResourceManager.GetString("Document_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical path.
        /// </summary>
        public static string Document_PhysicalPath {
            get {
                return ResourceManager.GetString("Document_PhysicalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        public static string Document_Slug {
            get {
                return ResourceManager.GetString("Document_Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique web identifier (slug) of the document is required..
        /// </summary>
        public static string Document_Slug_Required {
            get {
                return ResourceManager.GetString("Document_Slug_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique web identifier (slug) of the document cannot exceed {1} characters..
        /// </summary>
        public static string Document_Slug_StringLength {
            get {
                return ResourceManager.GetString("Document_Slug_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Document_Type {
            get {
                return ResourceManager.GetString("Document_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid documen type..
        /// </summary>
        public static string Document_Type_Invalid {
            get {
                return ResourceManager.GetString("Document_Type_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string DocumentType_File {
            get {
                return ResourceManager.GetString("DocumentType_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string DocumentType_Folder {
            get {
                return ResourceManager.GetString("DocumentType_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string DocumentType_Form {
            get {
                return ResourceManager.GetString("DocumentType_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DocumentType_Unknown {
            get {
                return ResourceManager.GetString("DocumentType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form entry.
        /// </summary>
        public static string FormField {
            get {
                return ResourceManager.GetString("FormField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string FormField_Help {
            get {
                return ResourceManager.GetString("FormField_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field help cannot exceed {1} characters..
        /// </summary>
        public static string FormField_Help_StringLength {
            get {
                return ResourceManager.GetString("FormField_Help_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique identifier.
        /// </summary>
        public static string FormField_Id {
            get {
                return ResourceManager.GetString("FormField_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid form entry identifier..
        /// </summary>
        public static string FormField_Id_XmlTagName {
            get {
                return ResourceManager.GetString("FormField_Id_XmlTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string FormField_IsRequired {
            get {
                return ResourceManager.GetString("FormField_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FormField_Name {
            get {
                return ResourceManager.GetString("FormField_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name cannot exceed {1} characters..
        /// </summary>
        public static string FormField_Name_StringLength {
            get {
                return ResourceManager.GetString("FormField_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FormField_Type {
            get {
                return ResourceManager.GetString("FormField_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is required..
        /// </summary>
        public static string FormField_Type_Required {
            get {
                return ResourceManager.GetString("FormField_Type_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        public static string FormField_Value {
            get {
                return ResourceManager.GetString("FormField_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field value cannot exceed {1} characters..
        /// </summary>
        public static string FormField_Value_StringLength {
            get {
                return ResourceManager.GetString("FormField_Value_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string FormFieldOption_Height {
            get {
                return ResourceManager.GetString("FormFieldOption_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FormFieldOption_Name {
            get {
                return ResourceManager.GetString("FormFieldOption_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option name cannot exceed {1} characters..
        /// </summary>
        public static string FormFieldOption_Name_StringLength {
            get {
                return ResourceManager.GetString("FormFieldOption_Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FormFieldOption_Type {
            get {
                return ResourceManager.GetString("FormFieldOption_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string FormFieldOption_Value {
            get {
                return ResourceManager.GetString("FormFieldOption_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option value cannot exceed {1} characters..
        /// </summary>
        public static string FormFieldOption_Value_StringLength {
            get {
                return ResourceManager.GetString("FormFieldOption_Value_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string FormFieldOption_Width {
            get {
                return ResourceManager.GetString("FormFieldOption_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string FormFieldOptionType_Image {
            get {
                return ResourceManager.GetString("FormFieldOptionType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string FormFieldOptionType_Text {
            get {
                return ResourceManager.GetString("FormFieldOptionType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormFieldOptionType_Unknown {
            get {
                return ResourceManager.GetString("FormFieldOptionType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string FormFieldOptionType_Video {
            get {
                return ResourceManager.GetString("FormFieldOptionType_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form entries.
        /// </summary>
        public static string FormFields {
            get {
                return ResourceManager.GetString("FormFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkboxes.
        /// </summary>
        public static string FormFieldType_Checkboxes {
            get {
                return ResourceManager.GetString("FormFieldType_Checkboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-down list.
        /// </summary>
        public static string FormFieldType_DropDownList {
            get {
                return ResourceManager.GetString("FormFieldType_DropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html section.
        /// </summary>
        public static string FormFieldType_HtmlSection {
            get {
                return ResourceManager.GetString("FormFieldType_HtmlSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page break.
        /// </summary>
        public static string FormFieldType_PageBreak {
            get {
                return ResourceManager.GetString("FormFieldType_PageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple choice.
        /// </summary>
        public static string FormFieldType_RadioButtons {
            get {
                return ResourceManager.GetString("FormFieldType_RadioButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section header.
        /// </summary>
        public static string FormFieldType_SectionHeader {
            get {
                return ResourceManager.GetString("FormFieldType_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text area.
        /// </summary>
        public static string FormFieldType_TextArea {
            get {
                return ResourceManager.GetString("FormFieldType_TextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text box.
        /// </summary>
        public static string FormFieldType_TextBox {
            get {
                return ResourceManager.GetString("FormFieldType_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FormFieldType_Unknown {
            get {
                return ResourceManager.GetString("FormFieldType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
    }
}
